version: "3.8"

services:
  fastapi_app:
    build: .
    ports:
      - "8000:80"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - fastapi_app
